name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

<<<<<<< HEAD
      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttihp26a
        with:
          pdk: ihp-sg13g2
          librelane-version: 3.0.0.dev44
=======
      - name: Read top module name
        id: top_module
        run: |
          echo TOP_MODULE=`yq '.project.top_module' info.yaml` | tee $GITHUB_OUTPUT

      - name: Create and publish the GDS artifact
        uses: TinyTapeout/tt-gds-action/custom_gds@ttihp26a
        with:
          top_module: ${{ steps.top_module.outputs.TOP_MODULE }}
          gds_path: gds/${{ steps.top_module.outputs.TOP_MODULE }}.gds
          lef_path: lef/${{ steps.top_module.outputs.TOP_MODULE }}.lef
          verilog_path: src/project.v
          pdk: ihp-sg13g2
>>>>>>> origin/ttihp-template

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttihp26a

<<<<<<< HEAD
  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@ttihp26a

=======
>>>>>>> origin/ttihp-template
  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
<<<<<<< HEAD
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
=======
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
>>>>>>> origin/ttihp-template
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@ttihp26a
